### ISSUE TITLE
Redraw Problems in urxvt, xterm

### ISSUE THREAD

**Issue by jebaum** [carbonfive/vimtronner#57]
Using urxvt and xterm, the screen continuously flashes/strobes, I assume at every redraw. The game is still playable but it's pretty hard on the eyes. Gnome-terminal works fine.

For what it's worth, I got this error log when I cloned the repo and ran `npm install`, but the game plays perfectly in gnome-terminal so it may not be related:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install' ]
2 info using npm@2.5.0
3 info using node@v0.10.36
4 verbose install where, deps [ '/home/james/vimtronner',
4 verbose install   [ 'socket.io',
4 verbose install     'socket.io-client',
4 verbose install     'commander',
4 verbose install     'moniker',
4 verbose install     'coffee-script',
4 verbose install     'mocha',
4 verbose install     'chai',
4 verbose install     'sinon',
4 verbose install     'sinon-chai',
4 verbose install     'grunt-cli',
4 verbose install     'grunt',
4 verbose install     'grunt-mocha',
4 verbose install     'grunt-mocha-test',
4 verbose install     'grunt-contrib-coffee',
4 verbose install     'grunt-contrib-watch' ] ]
5 verbose install where, peers [ '/home/james/vimtronner', [] ]
6 info preinstall vimtronner@0.0.9
7 warn package.json moniker@0.1.2 No repository field.
8 verbose already installed skipping coffee-script@ /home/james/vimtronner
9 verbose already installed skipping mocha@ /home/james/vimtronner
10 verbose already installed skipping chai@ /home/james/vimtronner
11 verbose already installed skipping sinon@ /home/james/vimtronner
12 verbose already installed skipping sinon-chai@ /home/james/vimtronner
13 verbose already installed skipping grunt-cli@~0.1.11 /home/james/vimtronner
14 verbose already installed skipping grunt@~0.4.2 /home/james/vimtronner
15 verbose already installed skipping grunt-mocha@~0.4.9 /home/james/vimtronner
16 verbose already installed skipping grunt-mocha-test@~0.8.2 /home/james/vimtronner
17 verbose already installed skipping grunt-contrib-coffee@~0.8.2 /home/james/vimtronner
18 verbose already installed skipping grunt-contrib-watch@~0.5.3 /home/james/vimtronner
19 verbose already installed skipping socket.io@ /home/james/vimtronner
20 verbose already installed skipping socket.io-client@ /home/james/vimtronner
21 verbose already installed skipping commander@ /home/james/vimtronner
22 verbose already installed skipping moniker@ /home/james/vimtronner
23 silly install resolved []
24 info build /home/james/vimtronner
25 verbose linkStuff [ false, false, false, '/home/james' ]
26 info linkStuff vimtronner@0.0.9
27 verbose linkBins vimtronner@0.0.9
28 verbose linkMans vimtronner@0.0.9
29 verbose rebuildBundles vimtronner@0.0.9
30 verbose rebuildBundles [ '.bin',
30 verbose rebuildBundles   'chai',
30 verbose rebuildBundles   'coffee-script',
30 verbose rebuildBundles   'commander',
30 verbose rebuildBundles   'grunt',
30 verbose rebuildBundles   'grunt-cli',
30 verbose rebuildBundles   'grunt-contrib-coffee',
30 verbose rebuildBundles   'grunt-contrib-watch',
30 verbose rebuildBundles   'grunt-mocha',
30 verbose rebuildBundles   'grunt-mocha-test',
30 verbose rebuildBundles   'mocha',
30 verbose rebuildBundles   'moniker',
30 verbose rebuildBundles   'sinon',
30 verbose rebuildBundles   'sinon-chai',
30 verbose rebuildBundles   'socket.io',
30 verbose rebuildBundles   'socket.io-client' ]
31 info install vimtronner@0.0.9
32 info postinstall vimtronner@0.0.9
33 info prepublish vimtronner@0.0.9
34 verbose stack Error: The package chai does not satisfy its siblings' peerDependencies requirements!
34 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:103:32
34 verbose stack     at /usr/lib/node_modules/npm/lib/install.js:225:5
34 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:138:5
34 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
34 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
34 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
34 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
34 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
34 verbose stack     at cb (/usr/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
34 verbose stack     at /usr/lib/node_modules/npm/node_modules/read-installed/read-installed.js:251:14
35 verbose cwd /home/james/vimtronner
36 error Linux 3.18.4-1-ARCH
37 error argv "/usr/bin/node" "/usr/bin/npm" "install"
38 error node v0.10.36
39 error npm  v2.5.0
40 error code EPEERINVALID
41 error peerinvalid The package chai does not satisfy its siblings' peerDependencies requirements!
41 error peerinvalid Peer sinon-chai@2.6.0 wants chai@>=1.9.2 <2
42 verbose exit [ 1, true ]
```

**Comment by lightstrike** [comment]
+1, experiencing this as well in xterm.
